import { HealthOverview } from "@/components/crm/health-overview";

const accounts = [
  {
    id: "1",
    name: "Globex Corporation",
    arr: 420_000,
    score: 82,
    previousScore: 79,
    renewalDate: "2027-02-01",
    owner: { name: "Maya Chen" },
    signals: ["Usage +12%", "Exec sponsor engaged"],
  },
  {
    id: "2",
    name: "Initech",
    arr: 186_000,
    score: 41,
    previousScore: 63,
    renewalDate: "2026-11-15",
    owner: { name: "Sam Ortiz" },
    signals: ["Usage -32%", "Champion left", "2 P1 tickets"],
  },
  {
    id: "3",
    name: "Umbrella Health",
    arr: 640_000,
    score: 71,
    previousScore: 74,
    renewalDate: "2027-05-30",
    owner: { name: "Ava Goldberg" },
    signals: ["Seat utilisation 68%"],
  },
  {
    id: "4",
    name: "Stark Logistics",
    arr: 95_000,
    score: 28,
    previousScore: 36,
    renewalDate: "2026-10-20",
    owner: { name: "Chris Doyle" },
    signals: ["No login in 21 days", "Invoice overdue"],
  },
  {
    id: "5",
    name: "Wayne Retail",
    arr: 310_000,
    score: 88,
    previousScore: 88,
    renewalDate: "2026-12-10",
    owner: { name: "Maya Chen" },
    signals: ["NPS 9", "Expansion in talks"],
  },
  {
    id: "6",
    name: "Hooli",
    arr: 250_000,
    score: 58,
    previousScore: 52,
    renewalDate: "2026-12-01",
    owner: { name: "Nia Brooks" },
    signals: ["Onboarding second team"],
  },
  {
    id: "7",
    name: "Vandelay Imports",
    arr: 48_000,
    score: 49,
    previousScore: 57,
    renewalDate: "2027-01-18",
    owner: { name: "Sam Ortiz" },
    signals: ["Support volume x3"],
  },
  {
    id: "8",
    name: "Tyrell Bio",
    arr: 510_000,
    score: 77,
    previousScore: 69,
    renewalDate: "2027-08-01",
    owner: { name: "Ava Goldberg" },
    signals: ["QBR completed"],
  },
  {
    id: "9",
    name: "Soylent Foods",
    arr: 72_000,
    score: 33,
    previousScore: 30,
    owner: { name: "Chris Doyle" },
    signals: ["Budget cut announced"],
  },
  {
    id: "10",
    name: "Wonka Labs",
    arr: 132_000,
    score: 64,
    previousScore: 71,
    renewalDate: "2026-11-02",
    owner: { name: "Nia Brooks" },
    signals: ["Feature request backlog"],
  },
];

export default function Example() {
  return <HealthOverview className="w-full max-w-[960px]" accounts={accounts} asOf="2026-09-25" />;
}
