import * as React from "react";
import { ProDiffViewer, type DiffComment, type DiffMode } from "@/components/crm/pro-diff-viewer";

const ENTITIES = ["Deal", "Contact", "Company", "Invoice", "Ticket", "Quote", "Task", "Lead"];
const FIELDS = ["amount", "stage", "ownerId", "closeDate", "status", "priority", "region", "score"];

/** Generates a 50k line TypeScript module (a codegen'd API client) and a reviewed revision. */
function generate(): { before: string; after: string } {
  const before: string[] = [
    "// AUTO-GENERATED by crm-sdk-gen. Do not edit by hand.",
    "import { request, type RequestOptions } " + "from '../transport';",
    "",
  ];
  const after: string[] = [...before];
  for (let i = 0; i < 5000; i++) {
    const entity = ENTITIES[i % ENTITIES.length]!;
    const field = FIELDS[(i * 7) % FIELDS.length]!;
    const name = `${entity}${Math.floor(i / ENTITIES.length)}`;
    const block: string[] = [
      `/** Fetches ${entity.toLowerCase()} records filtered by ${field}. */`,
      `export async function list${name}(filter: { ${field}?: string; limit?: number }, opts?: RequestOptions) {`,
      `  const params = new URLSearchParams();`,
      `  if (filter.${field}) params.set("${field}", filter.${field});`,
      `  params.set("limit", String(filter.limit ?? 50));`,
      `  const res = await request(\`/v2/${entity.toLowerCase()}s?\${params}\`, { method: "GET", ...opts });`,
      `  if (!res.ok) throw new Error(\`list${name} failed: \${res.status}\`);`,
      `  return (await res.json()) as { data: unknown[]; next?: string };`,
      `}`,
      "",
    ];
    before.push(...block);
    if (i % 97 === 13) {
      // Reviewed change: pagination cursor + retry on 429.
      after.push(
        block[0]!,
        block[1]!.replace("limit?: number }", "limit?: number; cursor?: string }"),
        block[2]!,
        block[3]!,
        `  params.set("limit", String(Math.min(filter.limit ?? 50, 200)));`,
        `  if (filter.cursor) params.set("cursor", filter.cursor);`,
        block[5]!.replace('method: "GET"', 'method: "GET", retry: { on: [429, 503], max: 3 }'),
        block[6]!,
        block[7]!,
        block[8]!,
        "",
      );
    } else if (i % 211 === 5) {
      after.push(block[0]!.replace("Fetches", "Lists"), ...block.slice(1));
    } else if (i % 503 === 400) {
      // removed endpoint
    } else after.push(...block);
  }
  return { before: before.join("\n"), after: after.join("\n") };
}

export default function Example() {
  const { before, after } = React.useMemo(generate, []);
  const [mode, setMode] = React.useState<DiffMode>("split");
  const [comments, setComments] = React.useState<DiffComment[]>([
    {
      id: "r1",
      side: "new",
      line: 136,
      author: { name: "Priya Nair" },
      body: "Cap at 200 matches the gateway limit. Can we read it from the OpenAPI spec instead of hardcoding?",
      createdAt: new Date(Date.now() - 42 * 60_000),
    },
  ]);
  return (
    <div className="bg-crm-bg p-4">
      <ProDiffViewer
        oldText={before}
        newText={after}
        language="ts"
        oldLabel="sdk/client.ts @ main"
        newLabel="sdk/client.ts @ feat/pagination"
        mode={mode}
        onModeChange={setMode}
        height={560}
        comments={comments}
        onAddComment={({ side, line, body }) =>
          setComments((cs) => [
            ...cs,
            {
              id: crypto.randomUUID(),
              side,
              line,
              body,
              author: { name: "You" },
              createdAt: new Date(),
            },
          ])
        }
      />
    </div>
  );
}
